### ISSUE TITLE
questionable quality

### ISSUE THREAD

**Issue by abjunk07** [vitogit/pgn-tactics-generator#4] opened 2020-02-24 19:06 UTC
This generator creates puzzles of questionable quality. The collection in https://github.com/xinyangz/chess-tactics-pgn that uses this generator has some issues:
+++++++++++++++++++++++++
Event "0708 49919"]
[Site "?"]
[Date "????.??.??"]
[Round "?"]
[White "?"]
[Black "solver"]
[Result "*"][SetUp "1"]
[FEN "2kr4/1p1r1p2/2p1p2p/8/P1P1Rp2/8/1P3PPP/R5K1 w KQkq - 0 1"]

1.Rxf4 Rd1+ 2.Rxd1 Rxd1# *
How can castle flags be KQkq when both kings are not in the initial positions??
How can result be * (both in Tags and in moves) when the game ends with checkmate?
+++++++++++++++++++++++++++++++++++
[Event "Rated Blitz game"]
[Site "https://lichess.org/zY14tLJJ"]
[Date "????.??.??"]
[Round "?"]
[White "RonaldFranco"]
[Black "A_R_A_K_E_L_Y_A_N"]
[Result "1-0"]
[BlackElo "1601"]
[BlackRatingDiff "-13"]
[ECO "C02"]
[FEN "6k1/p5pp/8/P2N4/8/4p3/RP3rPP/2bK4 b - - 3 30"]
[Opening "French Defense: Advance Variation, Nimzowitsch System"]
[SetUp "1"]
[Termination "Normal"]
[TimeControl "360+2"]
[UTCDate "2014.04.23"]
[UTCTime "19:07:56"]
[WhiteElo "1529"]
[WhiteRatingDiff "+13"]

30... Bxb2 31. Nxe3 Bc1 32. Rxf2 Bxe3 1-0
1st Black's move is a blunder and the whole puzzle is confusing. It starts with Black's move and ends with White win.

**Comment by vitogit** [comment] 2021-04-11 14:49
> How can castle flags be KQkq when both kings are not in the initial positions??
I can't reproduce this, the tactics generated from my pgn samples return the correct castling rights . It return the FEN from the game https://github.com/vitogit/pgn-tactics-generator/blame/master/modules/puzzle/puzzle.py#L29 so not sure how that's happening

> How can result be * (both in Tags and in moves) when the game ends with checkmate?
Now the result is the tactics results I will update the README to clarify this. Here is the code https://github.com/vitogit/pgn-tactics-generator/blame/master/modules/puzzle/puzzle.py#L33

>1st Black's move is a blunder and the whole puzzle is confusing. It starts with Black's move and ends with White win.
I think this is because the puzzles include the blunder move like some sites do (chess.com) I opened an issue to add the option to not include it https://github.com/vitogit/pgn-tactics-generator/issues/16

I will close this issue, but we can reopen if you have any question

**Closed by vitogit** 2021-04-11 14:49 UTC
Labels: good first issue
